Ranges/levels of quantitative and ordinal data 
- quantitative
    - max and min --> range
- ordinal
    - list of categories (unique values in column)
    - "one of many book titles such as... "

Mean and Median
- quantitative
    - average and middle functions
- ordinal 
    - positive, negative, neutral (neutral = middle)
    - not a mean or median for things like book titles

In [1]:
import pandas as pd

In [8]:
df = pd.read_csv("/Users/anikadas/Documents/DS4200/Once-Upon-a-Viz/top100_goodreads.csv")

In [9]:
df

,Goodreads_ID,Index,ISBN,Title,Author,Imprint,Publisher Group,Volume,Value,RRP,...,Publ Date,Product Class,book series,num pages,genres,shelves,num goodreads ratings,average goodreads ratings,goodreads rating distribution,num goodreads reviews
0,968.The_Da_Vinci_Code,1,9780552149518,"Da Vinci Code,The","Brown, Dan",Corgi Books,Transworld Grp,"4,522,025","£22,857,837.53",£7.99,...,1 Mar 2004,"F2.1 Crime, Thriller & Adventure",Robert Langdon #2,489.0,"{'genres': ['Fiction', 'Mystery', 'Thriller', ...","{'to-read': 416339, 'currently-reading': 19278...",2121534,3.88,"{'5 Stars': 731457, '4 Stars': 729405, '3 Star...",50199
1,72193.Harry_Potter_and_the_Philosopher_s_Stone,3,9780747532743,Harry Potter and the Philosopher's Stone,"Rowling, J. K.",Bloomsbury Publishing PLC,Bloomsbury Grp,"3,844,316","£19,853,187.43",£6.99,...,26 Jun 1997,Y2.1 Children's Fiction,Harry Potter #1,223.0,"{'genres': ['Fantasy', 'Fiction', 'Young Adult...","{'to-read': 1266232, 'currently-reading': 1870...",8334489,4.48,"{'5 Stars': 5420633, '4 Stars': 1906445, '3 St...",131608
2,15881.Harry_Potter_and_the_Chamber_of_Secrets,7,9780747538486,Harry Potter and the Chamber of Secrets,"Rowling, J. K.",Bloomsbury Publishing PLC,Bloomsbury Grp,"3,184,492","£16,224,021.98",£6.99,...,1 Apr 1999,Y2.1 Children's Fiction,Harry Potter #2,341.0,"{'genres': ['Fantasy', 'Fiction', 'Young Adult...","{'fantasy': 57513, 'favorites': 35022, 'fictio...",3214825,4.43,"{'5 Stars': 1906462, '4 Stars': 878809, '3 Sta...",63057
3,960.Angels_Demons,6,9780552150736,Angels and Demons,"Brown, Dan",Corgi Books,Transworld Grp,"3,096,850","£15,537,324.84",£7.99,...,1 Jul 2003,"F2.1 Crime, Thriller & Adventure",Robert Langdon #1,736.0,"{'genres': ['Fiction', 'Mystery', 'Thriller', ...","{'to-read': 656905, 'currently-reading': 16603...",2921948,3.92,"{'5 Stars': 1044923, '4 Stars': 989925, '3 Sta...",31070
4,2.Harry_Potter_and_the_Order_of_the_Phoenix,2,9780747551003,Harry Potter and the Order of the Phoenix,"Rowling, J. K.",Bloomsbury Publishing PLC,Bloomsbury Grp,"3,043,226","£33,925,431.19",£16.99,...,21 Jun 2003,Y2.1 Children's Fiction,Harry Potter #5,870.0,"{'genres': ['Fantasy', 'Young Adult', 'Fiction...","{'to-read': 400226, 'currently-reading': 62033...",2882627,4.50,"{'5 Stars': 1842775, '4 Stars': 726288, '3 Sta...",50446
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,18122.The_Amber_Spyglass,97,9780439993586,"Amber Spyglass,The:His Dark Materials S.","Pullman, Philip",Point,Scholastic Ltd. Grp,"653,615","£3,797,459.74",£6.99,...,14 Sep 2001,Y2.2 Young Adult Fiction,His Dark Materials #3,465.0,"{'genres': ['Fantasy', 'Young Adult', 'Fiction...","{'to-read': 76563, 'fantasy': 14450, 'currentl...",330635,4.09,"{'5 Stars': 141668, '4 Stars': 108294, '3 Star...",11851
83,33724.Can_You_Keep_a_Secret_,98,9780552771108,Can You Keep a Secret?,"Kinsella, Sophie",Black Swan,Transworld Grp,"652,788","£3,722,312.19",£7.99,...,17 Mar 2003,F1.1 General & Literary Fiction,NaN,374.0,"{'genres': ['Womens Fiction > Chick Lit', 'Rom...","{'to-read': 215711, 'currently-reading': 5324,...",408848,3.84,"{'5 Stars': 128674, '4 Stars': 138770, '3 Star...",13233
84,32349.Mutant_Message_Down_Under,99,9780552997034,Down Under,"Bryson, Bill",Black Swan,Transworld Grp,"646,515","£4,628,013.69",£8.99,...,6 Aug 2001,T8.5 Travel Writing,NaN,187.0,"{'genres': ['Fiction', 'Spirituality', 'Travel...","{'to-read': 6203, 'currently-reading': 480, 'f...",18999,3.76,"{'5 Stars': 6327, '4 Stars': 5913, '3 Stars': ...",1828
85,4701.A_Spot_of_Bother,100,9780099506928,"Spot of Bother,A","Haddon, Mark",Vintage,Random House Grp,"645,453","£3,949,459.94",£7.99,...,7 Jun 2007,F1.1 General & Literary Fiction,NaN,354.0,"{'genres': ['Fiction', 'Contemporary', 'Humor'...","{'to-read': 11868, 'fiction': 932, 'currently-...",34193,3.48,"{'5 Stars': 4944, '4 Stars': 12422, '3 Stars':...",3406
86,4391492-dear-fatty,101,9781846053443,Dear Fatty,"French, Dawn",Century,Random House Grp,"643,636","£6,330,572.88",£18.99,...,9 Oct 2008,T4.1A Autobiography: The Arts,NaN,368.0,"{'genres': ['Nonfiction', 'Biography', 'Biogra...","{'to-read': 4661, 'currently-reading': 368, 'n...",9728,3.79,"{'5 Stars': 2674, '4 Stars': 3581, '3 Stars': ...",743

In [10]:
df.describe()

,ISBN,num pages,num goodreads ratings,average goodreads ratings,num goodreads reviews
count,8.700000e+01,85.000000,8.700000e+01,87.000000,87.000000
mean,9.780648e+12,418.094118,9.555247e+05,3.990805,23633.252874
std,5.522238e+08,231.989512,1.472246e+06,0.340452,31576.557797
min,9.780006e+12,32.000000,2.000000e+00,3.000000,0.000000
25%,9.780141e+12,320.000000,1.527750e+04,3.780000,695.500000
50%,9.780553e+12,372.000000,2.765190e+05,3.940000,8836.000000
75%,9.780748e+12,489.000000,1.475886e+06,4.155000,41452.000000
max,9.781906e+12,1878.000000,8.334489e+06,5.000000,131608.000000

In [11]:
df['goodreads rating distribution']

0     {'5 Stars': 731457, '4 Stars': 729405, '3 Star...
1     {'5 Stars': 5420633, '4 Stars': 1906445, '3 St...
2     {'5 Stars': 1906462, '4 Stars': 878809, '3 Sta...
3     {'5 Stars': 1044923, '4 Stars': 989925, '3 Sta...
4     {'5 Stars': 1842775, '4 Stars': 726288, '3 Sta...
                            ...
82    {'5 Stars': 141668, '4 Stars': 108294, '3 Star...
83    {'5 Stars': 128674, '4 Stars': 138770, '3 Star...
84    {'5 Stars': 6327, '4 Stars': 5913, '3 Stars': ...
85    {'5 Stars': 4944, '4 Stars': 12422, '3 Stars':...
86    {'5 Stars': 2674, '4 Stars': 3581, '3 Stars': ...
Name: goodreads rating distribution, Length: 87, dtype: object

In [ ]:
df2 = pd.dataframe